stages:
- name: Build
  steps:
  - runScriptConfig:
      image: testharbor.bxhjhb.top/saas-test/maven:1.0
      shellScript: mvn clean install -Dmaven.test.skip=true
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: saas-test/example-greenhouse:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: testharbor.bxhjhb.top
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
notification: {}
